language: go
go_import_path: github.com/freundallein/loadbalancer

service:
  - docker

jobs:
  include:
    - stage: test
      name: "Unit tests"
      go: 1.13.x
      script: make test

    - stage: build
      name: "Distribute"
      go: 1.13.x
      if: branch = master
      script: make distribute

notifications:
  on_success: never
  on_failure: never