version: "3.5"

networks:
  network:
    name: example-network
    driver: bridge

services:
  loadbalancer:
    image: freundallein/go-lb:latest
    container_name: loadbalancer
    restart: always
    environment: 
      - PORT=8000
      - ADDRS=http://service-one:8000,http://service-two:8000,http://service-three:8000
      - STALE_TIMEOUT=1
    networks: 
      - network
    ports:
      - 8000:8000

  service-one:
    image: crccheck/hello-world
    container_name: hello-world-one
    restart: always
    networks: 
      - network

  service-two:
    image: crccheck/hello-world
    container_name: hello-world-two
    restart: always
    networks: 
      - network

  service-three:
    image: crccheck/hello-world
    container_name: hello-world-three
    restart: always
    networks: 
      - network
